parallel-jobs = 1
compression-level = 9
# remove-rv-integrations-checks = true

rv-brand = ""

cli-source = "j-hc/revanced-cli"
cli-version = "latest"

patches-source = "anddea/revanced-patches"
patches-version = "dev"

#========== YouTube ==========#

[YouTube-Premium]
enabled = true
app-name = "YouTube Premium"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
riplib = false

patcher-args = """\
  --rip-lib x86_64 --rip-lib x86 --rip-lib armeabi-v7a \
  -OpackageNameYouTube='h1toru.rvm.ytp' \
  -OappName='YouTube Premium' \
  -OrvxSettingsLabel='Premium options' -OinsertPosition='About' \
  -OdarkThemeBackgroundColor='#000000' -OlightThemeBackgroundColor='#FFFFFF' \
  """

included-patches = """\
  'Change version code' \
  'GmsCore support' \
  'Custom branding name for YouTube' \
  'Settings for YouTube' \
  'Theme' \
  'Return YouTube Dislike' \
  'Return YouTube Username' \
  'SponsorBlock' \
  """

excluded-patches = """\
  'Custom branding icon for YouTube' \
  'Custom header for YouTube' \
  'Alternative thumbnails' \
  'Enable debug logging' \
  'Translations for YouTube' \
  'Set Transcript Cookies' \
  'Disable layout updates' \
  'Spoof app version' \
  'Enable gradient loading screen' \
  'Force player buttons background' \
  'Hide Shorts dimming' \
  'Custom double tap length' \
  'Hide shortcuts' \
  """


apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/core-apks/apks/com.google.android.youtube"
